### PR TITLE
Add function, source and line number to log messages

### PR DESCRIPTION
**Pull request by paulcarlton-ww**
Remove previous revisions - WIP

### CODE REVIEW

**Review by sbernheim — COMMENTED** [review]
This does not seem sane to me.  Is there no provision for obtaining a stacktrace short of adding Trace and TraceExit calls to each function to artificially recreate the stack?

I also object to dumping logging functions in a Utils package.  You're just throwing things in a "junk drawer" rather put thought into where they really belong.  Junk drawers tend to fill up and just get larger over time until you don't even know what's in them anymore.

**Comment by paulcarlton-ww** [comment]
@sbernheim The tracing in and out of each function is not designed to replace stack traces, is designed to help with debugging 

Would you prefer if I renamed the utility package, logutils and moved the file utility functions to a fileutils package?

**Comment by paulcarlton-ww** [comment]
The tracing in and out of functions allows a developers to follow the path taken when investigating issues and is only enabled at highest level of tracing

**Review by sbernheim — APPROVED** [review]
I suppose we should put quotes around "helper" at this point, since those methods aren't actually helping anymore.

Approved - if you want to merge this to move forward and do the necessary.

**Pull request merged**
