### PR TITLE
get data from source controller

### PR DESCRIPTION
**Pull request by paulcarlton-ww**
Not complete yet

### CODE REVIEW

**Review by sbernheim — CHANGES_REQUESTED** [review]
Good start, but we need to start giving more thought to testing needs.  I have a strong bias towards instance methods and Providers/Helpers for testability reasons, but in this case the GetSourcePath and LinkData really do seem like instance methods.  The Layer object should be relatively lightweight when wrapping an AddonsLayer.

**Comment by paulcarlton-ww** [comment]
Agreed with most of your comments, I was thinking we need a separate package for this too. Will work on this tomorrow

**Comment by paulcarlton-ww** [comment]
working now, needs tests!
Feel free to change in anyway you want, maybe merge this then work on improving it in separate PR?

**Review by sbernheim — APPROVED** [review]
Working for you is good enuf for now.

**Pull request merged**
