### PR TITLE
Get Kraan Controller working in cluster

### PR DESCRIPTION
**Pull request by paulcarlton-ww**
This PR is an attempt to determine why the Kraan controller is working when run out of cluster from command line but not in a pod.

### CODE REVIEW

**Comment by paulcarlton-ww** [comment]
Raised issue in controller-runtime repo https://github.com/kubernetes-sigs/controller-runtime/issues/1193

**Comment by paulcarlton-ww** [comment]
@sbernheim fixed it, please merge
@richardcase @saada Thanks for your help, fixed now, I was setting the Namespace option

**Comment by paulcarlton-ww** [comment]
Turns out the issue was nothing to do with RBAC but the fact that early on I had copied code from the Flux team code without fully understanding it. The Namespace option was not set when running out of cluster so it defaulted to cluster scope. When I ran it in cluster I set the Namespace controller option to the namespace the pod was running in, meaning it only looked for Watched and Owned objects in that namespace rather than all namespaces.

**Review by sbernheim — APPROVED** [review]
LGTM!

**Pull request merged**
